expand validation to shared-bucket names
config.yaml validation now includes validation
of shared-bucket names

diff --git a/.github/workflows/delomaten.yaml b/.github/workflows/delomaten.yaml
--- a/.github/workflows/delomaten.yaml
+++ b/.github/workflows/delomaten.yaml
@@ -63,14 +63,14 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - name: Confirm Activation of 'delomaten'
+      - name: Confirm activation of 'shared-buckets' and 'delomaten' features
         run: |
-          result=$(yq e -o=json infra/projects.yaml | jq '.projects[] | select(.features | index("delomaten"))')
+           result=$(yq e -o=json infra/projects.yaml | jq '.projects[] | select(.features | index("shared-buckets")) | select(.features | index("delomaten"))')
 
-          if [ -z "$result" ]; then
-            echo "Error: The 'delomaten' feature is disabled for all projects."
-            exit 1
-          fi
+           if [ -z "$result" ]; then
+             echo "Error: No projects have both the 'shared-buckets' and 'delomaten' features enabled. Both are required to use 'delomaten'."
+             exit 1
+           fi
       - name: Set output variables
         id: step_output_variables
         run: |
@@ -198,6 +198,15 @@ jobs:
         if: ${{ needs.fetch_sources.outputs.all_sources_deleted != 'true' }}
         run: |
           git clone -b add-gha-for-delomaten https://github.com/statisticsnorway/dapla-shared-data-processor-build-scripts
+      - name: Fetch shared buckets
+        if: ${{ needs.fetch_sources.outputs.all_sources_deleted != 'true' }}
+        run: |
+          result=$(yq e -o=json infra/projects.yaml | jq '.projects[] | select(.features | index("shared-buckets"))')
+
+          if [ -z "$result" ]; then
+            echo "Error: The 'shared-buckets' feature is disabled for all projects."
+            exit 1
+          fi
       - name: Run tests for ${{ matrix.source }}
         if: ${{ needs.fetch_sources.outputs.all_sources_deleted != 'true' }}
         run: |
@@ -206,9 +215,10 @@ jobs:
           echo "Running test for source: $FOLDER_NAME-$ENV_NAME"
 
           export CONFIG_FILE_PATH="$GITHUB_WORKSPACE/automation/shared-data/$ENV_NAME/$FOLDER_NAME"
+          export SHARED_BUCKETS_FILE_PATH="$GITHUB_WORKSPACE/infra/projects/$ENV_NAME/iam.yaml"
           cd dapla-shared-data-processor-build-scripts/schema-validation
 
-          uv run python src/validate_config.py "$ENV_NAME" "$FOLDER_NAME" "$CONFIG_FILE_PATH"
+          uv run python src/validate_config.py "$ENV_NAME" "$FOLDER_NAME" "$CONFIG_FILE_PATH" "$SHARED_BUCKETS_FILE_PATH"
 
 #   plan:
 #     if: ${{ github.event_name == 'pull_request' }}
